development:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: project_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: project_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: project
  pool: 5
  timeout: 5000