# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd69238120f1d5d63ec7344dea3fb70294df155087f71d3835a7c673845ab383dfd6fadbb894b959481ce6ced3f037bf06cc5a8c2bcbed85857871c0d522efd1

test:
  secret_key_base: b41e5ccc1f317dbeea21e7bdb960015fc2d5cbf3d5a51afe16f32b641f41a6a91fedc908a5dccece2cb4ad29d93249654e86998e664a0c7076f4f04af7d93336

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
